books/urls.py
from django.urls import path
from . import views


# books/
# books/1/details

app_name = 'books'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:book_id>', views.detail, name='detail')
]

vidly/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('books/', include('books.urls')),
    path('search_manga/', views.search_manga, name='search_manga')
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from email.policy import default
from unittest.util import _MAX_LENGTH
from django.db import models
from django.utils import timezone


# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=255)
    description = models.CharField(null=True, max_length=500)
    author = models.CharField(max_length=255)
    editor = models.CharField(max_length=255)
    year_published = models.IntegerField()
    number_in_stock = models.IntegerField()
    daily_rate = models.FloatField(null=True)
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    date_created = models.DateTimeField(default=timezone.now)
    manga_image = models.ImageField(null=True, blank=True, upload_to='images/')

books/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404

import books
from . models import Book


# Create your views here.
def index(request):
    books = Book.objects.all()
    return render(request, 'books/index.html', {'books': books})


def detail(request, book_id):   
    book = get_object_or_404(Book, pk=book_id)
    return render(request, "books/detail.html", {'book': book})

vidly/views.py
from django.shortcuts import render

from books.models import Book, Genre


def home(request):
    return render(request, 'home.html')


def search_manga(request):
    if request.method == "POST":
        searched = request.POST[('searched')]
        mangas = Book.objects.filter(title__contains=searched)
        return render(request, 'books/search_manga.html', {'searched': searched, 'mangas': mangas})
    else:
        return render(request, 'books/search_manga.html', {})

books/templates/books/detail.html
{% extends 'base.html' %} {% block content %}

<style>
    div {
        text-align: center;
        display: flex;
        justify-content: center;
    }
    #info, #pic{
        margin-top: 80px;
        width: 350px;
    }
    #desc {
        margin-top: 80px;
        font-size: large;
        width: 800px;
    }

</style>
<div>
    <dl id="desc">
        <dt>Description</dt>
        <dd>{{ book.description }}</dd>
    </dl>
    <dl id="info">
        <dt>Title</dt>
        <dd>{{ book.title }}</dd>
        <dt>Genre</dt>
        <dd>{{ book.genre }}</dd>
        <dt>Author</dt>
        <dd>{{ book.author }}</dd>
        <dt>Editor</dt>
        <dd>{{ book.editor }}</dd>
        <dt>Year Published</dt>
        <dd>{{ book.year_published }}</dd>
        <dt>Stock</dt>
        <dd>{{ book.number_in_stock }}</dd>
        <dt>Daily Rate</dt>
        <dd>${{ book.daily_rate }}</dd>
    </dl>
    <dl id="pic">
        <dt>Volume Cover</dt>
        <dd><img src="{{ book.manga_image.url }}" width=300></dd>
    </dl>
</div>
{% endblock %}

books/templates/books/index.html
{% extends 'base.html' %} {% block content %}
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Genre</th>
      <th>Author</th>
      <th>Editor</th>
      <th>Year Published</th>
      <th>Stock</th>
      <th>Daily Rate</th>
    </tr>
  </thead>
  <tbody>
    {% for book in books %}
    <tr>
        <td>
          <a href="{% url 'books:detail' book.id %}">{{ book.title }}</a>
        </td>
        <td>{{ book.genre }}</td>
        <td>{{ book.author }}</td>
        <td>{{ book.editor }}</td>
        <td>{{ book.year_published }}</td>
        <td>{{ book.number_in_stock }}</td>
        <td>${{ book.daily_rate }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

books/templates/books/search_manga.html
{% extends 'base.html' %} {% block content %}
<style>
  h1 {
    text-align: center;
  }

  div {
    text-align: center;
    display: inline-block;
    width: 250px;
  }

  #link {
    color: black;
    font-size: 20px;
    font-weight: 500;
    text-decoration: none;
  }

  #link:hover {
    text-decoration: underline;
  }
</style>
{% if searched %}
<h1>Your Search Results:</h1>
<br />
{% for manga in mangas %}
<div>
  <a href="{% url 'books:detail' manga.id %}" style="text-decoration: none"
    ><img src="{{ manga.manga_image.url }}" width="200" /></a
  ><br />
  <a id="link" href="{% url 'books:detail' manga.id %}">{{ manga.title }}</a
  ><br />
</div>
{% endfor %} {% else %}
<h1>Hey! You Forgot To Search For A Manga...</h1>
{% endif %} {% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Book Store</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">Manga Book Store</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'books:index' %}">All Books</a>
            </li>
          </ul>
          <div class="collapse navbar-collapse justify-content-end">
            <form class="d-flex" role="search" method=POST action="{% url 'search_manga' %}">
              {% csrf_token %}
              <input class="form-control me-2" type="search" placeholder="Search Manga" aria-label="Search" name="searched">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form> 
          </div>
        </div>
      </div>
    </nav>
    <main class="container">{% block content %}{% endblock %}</main>

    <!-- Optional JavaScript here -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
  </body>
</html>

templates/home.html
{% extends 'base.html' %}


{% block content %}
<style>
    h1 {
        text-align: center;
        margin-top: 40px;
    }

    .description {
        text-align: center;
        margin-top: 50px;
        font-size: large;
        font-weight: 500;

    }

    .url {
        text-align: center;
        margin-top: 50px;
        font-size: 50px;
        display: block;
        margin-left: auto;
        margin-right: auto;
        width: 400px;
        color: black;
        background-color: lightsalmon;
    }

    #url {
        color: black;
    }
</style>

<h1>Welcome to the Manga Book Store!</h1>
<div class="description">
    <p>Here at the bookstore, you can find manga different manga thats available for renting out!<br>
        Either look up a book through the search bar or learn about books through its given description page. <br>
        To see the list of all the available books in stock, just click the link below and see our amazing collection!
    </p>
</div>
<div class="url">
    <a id= "url" href="{% url 'books:index' %}">ALL AVAILABLE BOOKS!</a>
</div>
{% endblock %}